<?php
/**
 * The header for our theme
 *
 * This is the template that displays all of the <head> section and everything up until <div id="content">
 *
 */


// Figure out the top-level page so we can get its components (and change nav colors if needed):
global $container_ID;

if ( is_front_page() || is_404() || is_search() ) {
	// The main home page or other "gloabl" pages like search and "page not found":
	$container_ID = bz_get_id_by_slug('home-container');
} elseif ( is_home() || is_single() || is_archive() ) {
	// The blog (which wp calls "home"), a list of posts ("archive"), or a single blog post:
	$container_ID = bz_get_id_by_slug('blog');
} elseif ( !empty($post->ID) ) {
	$container_ID = $post->ID;
} 

// Get the container post's format so we can change nav colors if needed:
$container_format = wp_get_post_terms($container_ID, 'format')[0]->slug;
$body_class = ($container_format) ? 'page-'.$container_format : '';


?><!DOCTYPE html>
<html <?php language_attributes(); ?> class="no-js no-svg">
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="profile" href="http://gmpg.org/xfn/11">
<link rel="shortcut icon" href="<?php echo get_stylesheet_directory_uri(); ?>/favicon.ico" />

<?php wp_head(); ?>
</head>

<body <?php body_class($body_class); // this adds an optional class to the default ones generated by wordpress. ?>>
<div id="page" class="site">
	<a class="skip-link screen-reader-text" href="#content"><?php _e( 'Skip to content', 'bz' ); ?></a>

	<header id="masthead" class="site-header" role="banner">

		<a id="logo" href="<?php echo get_home_url();?>">
			<img src="<?php echo get_template_directory_uri();?>/images/braven-logo.png" />
		</a>

		<?php 
		if ( has_nav_menu( 'top-primary' ) ) { 
			// Print the top menu if it exists:
			?>
			<div id="top-nav-btn">
				<div class="bar1"></div>
				<div class="bar2"></div>
				<div class="bar3"></div>
			</div>
			<nav class="navigation-top">
				<div class="wrap">

					<?php 
					wp_nav_menu( array( 'theme_location' => 'top-primary' ) );
					
					// and if there's anything in the secondary menu, print it too:
					if ( has_nav_menu( 'top-secondary' ) ) wp_nav_menu( array( 'theme_location' => 'top-secondary' ) );

					?> 
				</div><!-- .wrap -->
			</nav><!-- .navigation-top -->
			<?php 
		}

		 // social nav menu:
		include 'nav-social.php';
		
		if (has_post_thumbnail($container_ID) ) {

			// Get the format so we can control where the h1 is positioned
			if ( is_page() ) {
			$marquee_format = (wp_get_post_terms($post->ID, 'format')) ? wp_get_post_terms($post->ID, 'format')[0]->slug : '';
			}
			?>
			<section class="component marquee <?php echo $marquee_format; ?>">
				<?php echo get_the_post_thumbnail( $container_ID, 'marquee' ); ?>

				
				<div class="marquee-title">
					<h1>
						<?php echo get_the_excerpt($container_ID); ?>
					</h1>
					<?php 
						$caption = get_the_post_thumbnail_caption( $container_ID );
						if ($caption) {
							?>
							<div class="marquee-meta">
								<span class="caption">
									<?php echo $caption;?>
								</span>
									
							</div>			
							<?php
						}
					?>
				</div>
			</section>
			<?php
		}
		?>
	</header><!-- #masthead -->
	<div class="site-content-contain">
		<div id="content" class="site-content">
