<?php 
/**
 * Template for a single person's bio "square" and its content.
 * This is called from functions.php where a query is generated by a shortcode. 
 */

global $placeholder;

?>
<div class="mosaic-element bio <?php echo ($placeholder) ? $placeholder : ' hover-hint'; ?>">
	<div class="element-img">
		<?php 
		if ( has_post_thumbnail() && !$placeholder ) {
			$thumbatts = array(
				'title' => get_the_title(),
			);
			the_post_thumbnail('headshot', $thumbatts );
		} 
		?>
	</div>
	<div class="element-content hover-toggle">
		<h3><?php the_title();?></h3>
		<?php the_content();?>
	</div>
</div>
