<?php 
/**
 * This is called from functions.php where a query is generated by a shortcode. 
 */
?>
<div class="mosaic-element bio">
	<div class="element-img">
		<?php if ( has_post_thumbnail() ) {
			$thumbatts = array(
				'title' => get_the_title(),
			);
			the_post_thumbnail('headshot', $thumbatts );
		} ?>
	</div>
	<div class="element-content">
		<h3><?php the_title();?></h3>
		<?php the_content();?>
	</div>
</div>
